#include "parser.h"
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>

// Action constants.
enum action { number, add, subtract, multiply, divide };

// Error marker constants, and spellings.
enum marker { digit, operator, bracket, newline };
char *names[] = { "digit", "operator", "bracket", "newline" };

// Array to hold parser bytecode generated by pecan.
static byte code[] = {
// <pecan>
START, 39, BOTH, 2, GO, 38, AND, BOTH, 29, MAYBE, MANY, EITHER, 12, BOTH, 2,
GO, 41, AND, BOTH, 2, GO, 22, AND, ACT, add, OR, BOTH, 2, GO, 42, AND, BOTH,
2, GO, 9, AND, ACT, subtract, AND, GO, 57, STOP, START, 11, BOTH, 6, DO, AND,
MAYBE, MANY, GO, 34, AND, ACT, number, STOP, START, 11, BOTH, 2, MARK,
operator, AND, BOTH, 2, SET1, 43, AND, DROP, STOP, START, 11, BOTH, 2, MARK,
operator, AND, BOTH, 2, SET1, 45, AND, DROP, STOP, START, 9, BOTH, 2, MARK,
digit, AND, LOW1, 48, HIGH1, 57, STOP, START, 18, BOTH, 2, MARK, newline, AND,
BOTH, 4, MAYBE, ONE, STRING1, 13, AND, BOTH, 2, STRING1, 10, AND, DROP, STOP// </pecan>
};

// Stack structure to hold numbers during calculations.
struct stack { int top; int items[100]; };
typedef struct stack stack;

// Stack operations.
static inline void new(stack *s) { s->top = 0; }
static inline void push(stack *s, int n) { s->items[s->top++] = n; }
static inline int pop(stack *s) { return s->items[--s->top]; }

// Carry out an action.
static inline void *act(void *vs, int a, int n, char matched[n]) {
    stack *s = vs;
    int x, y;
    switch (a) {
        case number:
            x = 0;
            for (int i = 0; i < n; i++) x = x * 10 + (matched[i] - '0');
            push(s, x); break;
        case add: y = pop(s); x = pop(s); push(s, x + y); break;
        case subtract: y = pop(s); x = pop(s); push(s, x - y); break;
        case multiply: y = pop(s); x = pop(s); push(s, x * y); break;
        case divide: y = pop(s); x = pop(s); push(s, x / y); break;
    }
    return s;
}

int main() {
    char input[100];
    fgets(input, 100, stdin);
    stack sData;
    stack *s = &sData;
    err eData;
    err *e = &eData;
    new(s);
    parse(0, code, input, NULL, act, s, e);
    if (e->ok) printf("%d\n", pop(s));
    else {
        report(e, "Syntax error:\n", "Error: expecting ", ", ", "\n", names);
        reportLine(e, input);
        reportColumn(e);
    }
}
