#include "scan.h"
#include "interpret.h"
#include <stdio.h>
#include <stdlib.h>

// The actions are the token tags, plus 'tokens'. The names are for tracing.
enum { tokens = bad + 1 };
char *names[] = {
    "number", "plus", "minus", "times", "over", "open", "close", "bad", "tokens"
};

// Array to hold scanner bytecode generated by pecan.
static byte code[] = {
// <pecan>
// </pecan>
};

// Structure to hold the input and list of tokens.
struct state { char *input; int length, max; token *list; };
typedef struct state state;

// Create a new state with a given input and empty token list of size n.
static state *newState(char *in, int n) {
    state *s = malloc(sizeof(state));
    *s = (state) {
        .input = in, .length = 0, .max = n, .list = malloc(n * sizeof(token))
    };
    return s;
}

// Add a token, doubling the size of the list if necessary.
static inline void add(state *s, int tag, int p, int n) {
    if (s->length >= s->max) {
        s->max = s->max * 2;
        s->list = realloc(s->list, s->max * sizeof(token));
    }
    token *t = &s->list[s->length++];
    *t = (token) { .tag = tag, .at = p, .length = n };
}

// Carry out an action. The action is normally a token tag.
static void act(void *vs, int a, int p, int n) {
    state *s = vs;
    if (a == tokens) return;
    add(s, a, p, n);
}

token *scan(char *input) {
    state *s = newState(input, 8);
    result *r = malloc(sizeof(result));
    parseText(code, input, act, s, r);
    add(s, -1, 0, 0);
    free(r);
    token *ts = s->list;
    free(s);
    return ts;
}

#ifdef scanTest

// Running the scanner interactively on its own.
int main() {
    char input[100];
    printf("Type a sum: ");
    char *out = fgets(input, 100, stdin);
    if (out == NULL) printf("Can't read stdin\n");
    token *ts = scan(input);
    for (int i = 0; ts[i].tag >= 0; i++) {
        printf("%s %d %d\n", names[ts[i].tag], ts[i].at, ts[i].length);
    }
    free(ts);
}

#endif
