#include "parser.h"
#include <stdio.h>

// Action constants.
enum action { number, add, subtract, multiply, divide };

// Error marker constants, and spellings.
enum marker { digit, operator, bracket, newline };
char *names[] = { "digit", "operator", "bracket", "newline" };

// Array to hold parser bytecode generated by pecan.
static byte code[] = {
// <pecan>
// </pecan>
};

// Stack structure to hold numbers during calculations.
struct stack { int top; int items[100]; };
typedef struct stack stack;

// Stack operations.
static inline void new(stack *s) { s->top = 0; }
static inline void push(stack *s, int n) { s->items[s->top++] = n; }
static inline int pop(stack *s) { return s->items[--s->top]; }

// Carry out an action.
static inline void act(void *vs, int a, int n, char matched[n]) {
    stack *s = vs;
    int x, y;
    switch (a) {
        case number:
            x = 0;
            for (int i = 0; i < n; i++) x = x * 10 + (matched[i] - '0');
            push(s, x); break;
        case add: y = pop(s); x = pop(s); push(s, x + y); break;
        case subtract: y = pop(s); x = pop(s); push(s, x - y); break;
        case multiply: y = pop(s); x = pop(s); push(s, x * y); break;
        case divide: y = pop(s); x = pop(s); push(s, x / y); break;
    }
}

int main() {
    char input[100];
    fgets(input, 100, stdin);
    stack sData;
    stack *s = &sData;
    result rData;
    result *r = &rData;
    new(s);
    parseC(code, input, act, s, r);
    if (r->ok) printf("%d\n", pop(s));
    else report(r, "Syntax error:\n", "Error: expecting ", ", ", "\n", names);
}
