#include "parser.h"
#include <stdio.h>

// Action constants.
enum action { number, add, subtract, multiply, divide };

// Error marker constants, and spellings.
enum marker { digit, operator, bracket, newline };
char *names[] = { "digit", "operator", "bracket", "newline" };

// Array to hold parser bytecode generated by pecan.
static byte code[] = {
// <pecan>
START, 12, BOTH, 2, GO, 226, AND, BOTH, 2, GO, 6, AND, GO, 229, STOP, START,
34, BOTH, 2, GO, 33, AND, MAYBE, MANY, EITHER, 12, BOTH, 2, GO, 100, AND,
BOTH, 2, GO, 19, AND, ACT, add, OR, BOTH, 2, GO, 102, AND, BOTH, 2, GO, 6,
AND, ACT, subtract, STOP, START, 34, BOTH, 2, GO, 33, AND, MAYBE, MANY,
EITHER, 12, BOTH, 2, GO, 93, AND, BOTH, 2, GO, 19, AND, ACT, multiply, OR,
BOTH, 2, GO, 95, AND, BOTH, 2, GO, 6, AND, ACT, divide, STOP, START, 17,
EITHER, 2, GO, 16, OR, BOTH, 2, GO, 90, AND, BOTH, 2, BACK, 88, AND, GO, 97,
STOP, START, 16, BOTH, 6, DO, AND, MAYBE, MANY, GO, 101, AND, BOTH, 2, ACT,
number, AND, GO, 105, STOP, START, 12, BOTH, 2, MARK, operator, AND, BOTH, 2,
SET1, 43, AND, GO, 90, STOP, START, 12, BOTH, 2, MARK, operator, AND, BOTH, 2,
SET1, 45, AND, GO, 75, STOP, START, 12, BOTH, 2, MARK, operator, AND, BOTH, 2,
SET1, 42, AND, GO, 60, STOP, START, 12, BOTH, 2, MARK, operator, AND, BOTH, 2,
SET1, 47, AND, GO, 45, STOP, START, 12, BOTH, 2, MARK, bracket, AND, BOTH, 2,
SET1, 40, AND, GO, 30, STOP, START, 12, BOTH, 2, MARK, bracket, AND, BOTH, 2,
SET1, 41, AND, GO, 15, STOP, START, 9, BOTH, 2, MARK, digit, AND, LOW1, 48,
HIGH1, 57, STOP, START, 8, BOTH, 4, MAYBE, MANY, SET1, 32, AND, DROP, STOP,
START, 18, BOTH, 2, MARK, newline, AND, BOTH, 4, MAYBE, ONE, STRING1, 13, AND,
BOTH, 2, STRING1, 10, AND, DROP, STOP
// </pecan>
};

// Stack structure to hold numbers during calculations.
struct stack { int top; int items[100]; };
typedef struct stack stack;

// Stack operations.
static inline void new(stack *s) { s->top = 0; }
static inline void push(stack *s, int n) { s->items[s->top++] = n; }
static inline int pop(stack *s) { return s->items[--s->top]; }

// Carry out an action.
static inline void act(void *vs, int a, int n, char matched[n]) {
    stack *s = vs;
    int x, y;
    switch (a) {
        case number:
            x = 0;
            for (int i = 0; i < n; i++) x = x * 10 + (matched[i] - '0');
            push(s, x); break;
        case add: y = pop(s); x = pop(s); push(s, x + y); break;
        case subtract: y = pop(s); x = pop(s); push(s, x - y); break;
        case multiply: y = pop(s); x = pop(s); push(s, x * y); break;
        case divide: y = pop(s); x = pop(s); push(s, x / y); break;
    }
}

int main() {
    char input[100];
    fgets(input, 100, stdin);
    stack sData;
    stack *s = &sData;
    err eData;
    err *e = &eData;
    new(s);
    parse(0, code, input, NULL, act, s, e);
    if (e->ok) printf("%d\n", pop(s));
    else report(e, "Syntax error:\n", "Error: expecting ", ", ", "\n", names);
}
